language: go

go:
 - 1.18

install:
- go get -v -t ./...
- go install -v ./...

before_script:
- go install github.com/mattn/goveralls@latest

script:
- go vet ./...
- go build ./...
- go test ./... -cover=1 -coverprofile=_c.cov
# TODO: enable after passing.
# - go test ./... -race

after_script:
- $GOPATH/bin/goveralls -service=travis-ci -coverprofile=_c.cov
