# A ClusterIP service to make stats-pipeline available to other pods.
apiVersion: v1
kind: Service
metadata:
  name: stats-pipeline-service
spec:
  type: ClusterIP
  selector:
    run: stats-pipeline
  ports:
    - protocol: TCP
      port: 8080
