
# A ClusterIP service to make stats-pipeline available to other pods.
apiVersion: v1
kind: Service
metadata:
  name: hopannotation1-export-service
spec:
  type: ClusterIP
  selector:
    run: hopannotation1-export
  ports:
    - protocol: TCP
      port: 8080
